import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { type RouterOutputs, api } from "~/utils/api";

type Station = RouterOutputs["stations"]["getAll"][number];
const StationView = (props: Station) => {
    return (
        <div>
            <h2>{props.name_fin}</h2>
        </div>
    )
}

const StationList = () => {
    const { data, isLoading: stationsLoading } = api.stations.getAll.useQuery();

    if (stationsLoading) return <div>Loading...</div>;
    if (!data) return <div>Something went wrong</div>;

    return (
        <div className="flex flex-col border justify-center">
            {data.map((station) => (
                <StationView key={station.id} {...station} />
            ))}
        </div>
    );
}

const Stations: NextPage = () => {
    api.stations.getAll.useQuery();

    return (
        <>
            <Head>
                <title>Stations | Bike App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col bg-slate-600">
                <Link href="..">Home</Link>
                <h1>Stations</h1>
                <div>
                    <StationList />
                </div>
            </main>
        </>
    );
};

export default Stations;

