import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { type RouterOutputs, api } from "~/utils/api";

type Station = RouterOutputs["stations"]["getAll"][number];
const StationView = (props: Station) => {
    return (
        <li>
            <div className="flex border-b border-slate-300 gap-4">
                <Link href={`/stations/${props.id}`}>
                    <h2 className="px-4">{props.name_fin}</h2>
                </Link>
            </div>
        </li>
    )
}

const StationList = () => {
    const { data, isLoading: stationsLoading } = api.stations.getAll.useQuery();

    if (stationsLoading) return <div>Loading...</div>;
    if (!data) return <div>Something went wrong</div>;

    return (
        <div className="flex flex-col border justify-center rounded bg-sky-600">
            <ul>
                {data.map((station) => (
                    <StationView key={station.id} {...station} />
                ))}
            </ul>
        </div>
    );
}

const Stations: NextPage = () => {
    api.stations.getAll.useQuery();

    return (
        <>
            <Head>
                <title>Stations | Bike App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col bg-slate-200">
                <Link
                    className="border border-slate-400 text-slate-300 px-2 py-1
                    rounded hover:bg-slate-400 focus-within:bg-slate-700 outline-none"
                    href=".."
                >
                    Home
                </Link>
                <div className="h-20 py-4 mb-2">
                    <h1>Stations</h1>
                    <div className="container flex flex-col justify-center">
                        <StationList />
                    </div>
                </div>
            </main>
        </>
    );
};

export default Stations;

