import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { type RouterOutputs, api } from "~/utils/api";

type Journey = RouterOutputs["journeys"]["getAll"][number]
const JourneyView = (props: Journey) => {
    return (
        <div className="flex border-b border-slate-300">
            <div className="flex flex-col">
                <span className="text-2xl gap-2">{`${props.departure_station_name} - ${props.return_station_name}`}</span>
            </div>
            <div className="flex gap-2">
                <span>{`Distance (m): ${props.covered_distance}`}</span>
                <span>{`Duration (sec): ${props.duration}`}</span>
            </div>
        </div>
    );
}

const Feed = () => {
    const {data, isLoading: journeysLoading } = api.journeys.getAll.useQuery();

    if (journeysLoading) return <div>Loading...</div>;
    if (!data) return <div>Something went wrong</div>;

    return (
        <div className="flex flex-col">
            {data.map((journey) => (
                <JourneyView key={journey.id} {...journey} />
            ))}
        </div>
    );
}

const Home: NextPage = () => {
    api.journeys.getAll.useQuery();

    return (
        <>
            <Head>
                <title>Bike App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex min-h-screen flex-col bg-slate-600">
                <header className="flex bg-slate-800 justify-between items-center mb-4">
                    <h1 className="text-2xl font-extrabold">Bike App</h1>
                    <Link
                        className="border border-slate-300 text-slate-300 px-2 py-1
                rounded hover:bg-slate-700 focus-within:bg-slate-700 outline-none"
                        href="/new"
                    >
                        Add Journey
                    </Link>
                </header>
                <div className="container flex flex-col gap-12 px-4 py-16 ">
                    <div className="items-center justify-center">
                        <h2 className="text-lg font-bold">Journeys</h2>
                    </div>
                    <div>
                        <Feed />
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;

